### ISSUE TITLE
Move high resolution package to a separate repository

### ISSUE THREAD

**Issue by pvandommelen** [FreeAllegiance/Artwork#28]
I would like to move everything inside Textures/ to a separate repository. This makes it clear what the steam version actually contains. It also makes it easier for us to point at a high resolution package to download, which can then be easily downloaded using github's interface.

Something like FreeAllegiance/ModHighResolution, indicating the intent of making it into an official mod/dlc whenever we get the steam workshop going on.

@BackTrak @LordBlacksun @Bunnywabbit

**Comment by LordBlacksun** [comment]
Agreed. Want me to host it, then you can fork?

**Comment by pvandommelen** [comment]
If you can prepare something, yes please

**Comment by LordBlacksun** [comment]
https://github.com/LordBlacksun/Allegiance-high-resolution-texture-files
